from __future__ import annotations

from .schemas import TransactionScoreRequest


def demo_transactions() -> list[TransactionScoreRequest]:
    return [
        TransactionScoreRequest(
            external_id="demo-001",
            amount=38.75,
            currency="GBP",
            merchant_name="City Grocer",
            merchant_category="groceries",
            entry_mode="chip",
            country="GB",
            customer_tenure_days=520,
            account_age_days=520,
            email_age_days=500,
            card_present=True,
            is_international=False,
            ip_risk_score=0.08,
            velocity_1h=1,
            velocity_24h=3,
        ),
        TransactionScoreRequest(
            external_id="demo-002",
            amount=620.0,
            currency="GBP",
            merchant_name="Orbit Gadgets",
            merchant_category="electronics",
            entry_mode="online",
            country="GB",
            customer_tenure_days=24,
            account_age_days=24,
            email_age_days=2,
            card_present=False,
            is_international=False,
            ip_risk_score=0.84,
            velocity_1h=4,
            velocity_24h=9,
        ),
        TransactionScoreRequest(
            external_id="demo-003",
            amount=890.0,
            currency="GBP",
            merchant_name="Sunset Travel",
            merchant_category="travel",
            entry_mode="manual",
            country="BR",
            customer_tenure_days=60,
            account_age_days=60,
            email_age_days=55,
            card_present=False,
            is_international=True,
            ip_risk_score=0.76,
            velocity_1h=3,
            velocity_24h=6,
        ),
        TransactionScoreRequest(
            external_id="demo-004",
            amount=79.0,
            currency="GBP",
            merchant_name="Corner Fuel",
            merchant_category="fuel",
            entry_mode="tap",
            country="GB",
            customer_tenure_days=860,
            account_age_days=860,
            email_age_days=845,
            card_present=True,
            is_international=False,
            ip_risk_score=0.12,
            velocity_1h=2,
            velocity_24h=5,
        ),
        TransactionScoreRequest(
            external_id="demo-005",
            amount=410.0,
            currency="GBP",
            merchant_name="PlayGrid",
            merchant_category="gaming",
            entry_mode="keyed",
            country="NG",
            customer_tenure_days=13,
            account_age_days=13,
            email_age_days=1,
            card_present=False,
            is_international=True,
            ip_risk_score=0.92,
            velocity_1h=7,
            velocity_24h=14,
        ),
    ]
